apiVersion: v1
kind: ConfigMap
metadata:
    name: backend-config
    namespace: ${KUBE_NAMESPACE}
data:
  FRONTEND_PATH: ${FRONTEND_PATH}
  STORAGE_SERVICE_INTERNAL_URL: storage-service
  STORAGE_SERVICE_PORT: "8000"