apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: backend-ingress
    namespace: ${KUBE_NAMESPACE}
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    tls:
        -   hosts:
                - ${KUBE_API_DOMAIN}
            secretName: letsencrypt-cluster-certificate-tls
    rules:
        -   host: ${KUBE_API_DOMAIN}
            http:
                paths:
                    -   path: /
                        pathType: Prefix
                        backend:
                            service:
                                name: backend-service
                                port:
                                    number: 8070